-- =====================================================================
-- CG DULCES · Esquema de base de datos (Supabase / PostgreSQL)
-- =====================================================================
-- Este archivo reconstruye el esquema tal como lo usa index.html HOY,
-- y agrega columnas/tablas nuevas para las funciones pedidas.
--
-- ⚠ IMPORTANTE: tu base YA existe. NO ejecutes esto entero a ciegas.
--   1. Todo lo que crea tablas/columnas usa "IF NOT EXISTS" o
--      "ADD COLUMN IF NOT EXISTS": es seguro correrlo sobre la base actual.
--   2. Antes de aplicar, sacá una copia (Dashboard → Database → Backups,
--      o el botón "Descargar copia de seguridad" de la app).
--   3. Aplicá en este orden: 01_schema → 02_security → 03_rpc →
--      04_triggers → 05_views. Ver docs/MIGRATION.md.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Configuración (clave/valor)
-- ---------------------------------------------------------------------
create table if not exists public.configuracion (
  clave text primary key,
  valor text
);

-- ---------------------------------------------------------------------
-- Usuarios de la app (vendedores que aparecen al confirmar una venta)
-- ---------------------------------------------------------------------
create table if not exists public.usuarios_app (
  id          bigint generated by default as identity primary key,
  nombre      text not null unique,
  created_at  timestamptz not null default now()
);
-- NUEVO: identidad real por vendedor (Fase 2 de seguridad)
alter table public.usuarios_app add column if not exists rol        text not null default 'vendedor';   -- 'duena' | 'vendedor'
alter table public.usuarios_app add column if not exists pin_hash   text;                                -- PIN 4-6 dígitos, hasheado (nunca en texto plano)
alter table public.usuarios_app add column if not exists activo     boolean not null default true;
alter table public.usuarios_app add column if not exists auth_uid   uuid;                                -- se enlaza con auth.users cuando cada vendedor tenga su login
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'usuarios_app_rol_chk') then
    alter table public.usuarios_app add constraint usuarios_app_rol_chk
      check (rol in ('duena','vendedor')) not valid;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Categorías
-- ---------------------------------------------------------------------
create table if not exists public.categorias (
  id      bigint generated by default as identity primary key,
  nombre  text not null unique
);
alter table public.categorias add column if not exists orden  int;
alter table public.categorias add column if not exists color  text;

-- ---------------------------------------------------------------------
-- Proveedores
-- ---------------------------------------------------------------------
create table if not exists public.proveedores (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  telefono    text,
  created_at  timestamptz not null default now()
);
alter table public.proveedores add column if not exists telefono text;   -- por si acaso: refuerzo defensivo

-- ---------------------------------------------------------------------
-- Clientes
-- ---------------------------------------------------------------------
create table if not exists public.clientes (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  telefono    text,
  created_at  timestamptz not null default now()
);
alter table public.clientes add column if not exists telefono text;   -- la app original nunca lo usó: puede faltar en tablas ya existentes
alter table public.clientes add column if not exists notas text;

-- ---------------------------------------------------------------------
-- Productos e insumos
-- ---------------------------------------------------------------------
create table if not exists public.productos (
  id                    bigint generated by default as identity primary key,
  nombre                text not null,
  categoria_id          bigint references public.categorias(id) on delete set null,
  presentacion          text,
  es_insumo             boolean not null default false,
  favorito              boolean not null default false,
  usa_pajita            boolean not null default false,
  activo                boolean not null default true,
  stock                 numeric not null default 0,
  stock_minimo          numeric not null default 0,
  precio_venta          numeric not null default 0,
  costo_ultimo          numeric not null default 0,
  producto_base         text,          -- 'Balde Helado' | 'Cobertura' | null
  bolas_vendidas_actual numeric not null default 0,
  equivalencia_bolas    numeric,       -- factor de conversión al comprar (ej: 1 balde => N bolas)
  created_at            timestamptz not null default now()
);
-- NUEVO
alter table public.productos add column if not exists foto_url            text;
alter table public.productos add column if not exists precio_mayorista    numeric;      -- null = no tiene precio mayorista
alter table public.productos add column if not exists mayorista_min_cant  numeric;      -- desde cuántas unidades aplica
alter table public.productos add column if not exists vida_util_dias      int;          -- para control de vencimientos por lote
alter table public.productos add column if not exists proveedor_habitual_id bigint references public.proveedores(id) on delete set null;

create index if not exists idx_productos_activo    on public.productos(activo);
create index if not exists idx_productos_categoria on public.productos(categoria_id);
create index if not exists idx_productos_insumo    on public.productos(es_insumo);

-- ---------------------------------------------------------------------
-- Promociones
-- ---------------------------------------------------------------------
create table if not exists public.promociones (
  id                   bigint generated by default as identity primary key,
  nombre               text not null,
  categoria_id         bigint references public.categorias(id) on delete cascade,
  producto_id          bigint references public.productos(id)  on delete cascade,
  cantidad_requerida   int not null default 2,
  precio_promocional   numeric not null default 0,
  activo               boolean not null default true,
  created_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Recetas (insumos que lleva 1 unidad de un producto terminado)
-- ---------------------------------------------------------------------
create table if not exists public.recetas (
  id                    bigint generated by default as identity primary key,
  producto_terminado_id bigint not null references public.productos(id) on delete cascade,
  insumo_id             bigint not null references public.productos(id) on delete cascade,
  cantidad              numeric not null,
  created_at            timestamptz not null default now()
);
create index if not exists idx_recetas_terminado on public.recetas(producto_terminado_id);

-- ---------------------------------------------------------------------
-- Caja
-- ---------------------------------------------------------------------
create table if not exists public.caja (
  id                bigint generated by default as identity primary key,
  estado            text not null default 'abierta',   -- 'abierta' | 'cerrada'
  apertura_efectivo numeric not null default 0,
  apertura_banco    numeric not null default 0,
  cierre_efectivo   numeric,
  cierre_banco      numeric,
  fecha_apertura    timestamptz not null default now(),
  fecha_cierre      timestamptz,
  registrado_por    text
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'caja_estado_chk') then
    alter table public.caja add constraint caja_estado_chk check (estado in ('abierta','cerrada')) not valid;
  end if;
end $$;
create unique index if not exists uq_caja_una_abierta on public.caja(estado) where estado = 'abierta';

create table if not exists public.caja_movimientos (
  id           bigint generated by default as identity primary key,
  caja_id      bigint not null references public.caja(id) on delete cascade,
  tipo         text not null,                 -- venta | cobro | ingreso_extra | retiro | compra
  monto        numeric not null,
  medio_pago   text,                          -- efectivo | transferencia | qr
  venta_id     bigint,
  compra_id    bigint,
  descripcion  text,
  fecha        timestamptz not null default now()
);
alter table public.caja_movimientos add column if not exists compra_id bigint;
create index if not exists idx_cajamov_caja on public.caja_movimientos(caja_id);
create index if not exists idx_cajamov_venta on public.caja_movimientos(venta_id);
create index if not exists idx_cajamov_compra on public.caja_movimientos(compra_id);

-- ---------------------------------------------------------------------
-- Ventas
-- ---------------------------------------------------------------------
create table if not exists public.ventas (
  id                  bigint generated by default as identity primary key,
  subtotal            numeric,
  descuento_total     numeric not null default 0,
  total               numeric not null,
  medio_pago          text,                    -- efectivo | transferencia | qr | mixto | fiado
  es_fiado            boolean not null default false,
  registrado_por      text,
  cliente_id          bigint references public.clientes(id) on delete set null,
  monto_efectivo      numeric not null default 0,
  monto_transferencia numeric not null default 0,
  created_at          timestamptz not null default now()
);
alter table public.ventas add column if not exists usuario_app_id bigint references public.usuarios_app(id) on delete set null;
alter table public.ventas add column if not exists es_mayorista   boolean not null default false;
alter table public.ventas add column if not exists pedido_id      bigint;   -- si nació de un encargo
create index if not exists idx_ventas_created on public.ventas(created_at);
create index if not exists idx_ventas_cliente on public.ventas(cliente_id);
create index if not exists idx_ventas_fiado   on public.ventas(es_fiado) where es_fiado;

create table if not exists public.venta_items (
  id              bigint generated by default as identity primary key,
  venta_id        bigint not null references public.ventas(id) on delete cascade,
  producto_id     bigint references public.productos(id) on delete set null,
  cantidad        numeric not null,
  precio_unitario numeric,
  costo_unitario  numeric,
  descuento       numeric not null default 0,
  subtotal        numeric
);
create index if not exists idx_ventaitems_venta    on public.venta_items(venta_id);
create index if not exists idx_ventaitems_producto on public.venta_items(producto_id);

-- Cuentas compartidas (dividir una venta entre varios clientes)
create table if not exists public.venta_repartos (
  id          bigint generated by default as identity primary key,
  venta_id    bigint not null references public.ventas(id) on delete cascade,
  cliente_id  bigint not null references public.clientes(id) on delete cascade,
  monto       numeric not null,
  created_at  timestamptz not null default now()
);
create index if not exists idx_repartos_venta   on public.venta_repartos(venta_id);
create index if not exists idx_repartos_cliente on public.venta_repartos(cliente_id);

-- ---------------------------------------------------------------------
-- Cobros de fiado
-- ---------------------------------------------------------------------
create table if not exists public.cobros (
  id             bigint generated by default as identity primary key,
  venta_id       bigint references public.ventas(id) on delete set null,
  cliente_id     bigint references public.clientes(id) on delete set null,
  monto          numeric not null,
  medio_pago     text,
  registrado_por text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_cobros_venta   on public.cobros(venta_id);
create index if not exists idx_cobros_cliente on public.cobros(cliente_id);
create index if not exists idx_cobros_created on public.cobros(created_at);

-- ---------------------------------------------------------------------
-- Compras a proveedores
-- ---------------------------------------------------------------------
create table if not exists public.compras (
  id                  bigint generated by default as identity primary key,
  proveedor_id        bigint references public.proveedores(id) on delete set null,
  tipo                text,
  total               numeric not null,
  descuento           numeric not null default 0,
  medio_pago          text,
  monto_efectivo      numeric not null default 0,
  monto_transferencia numeric not null default 0,
  comprobante_url     text,
  registrado_por      text,
  created_at          timestamptz not null default now()
);
create index if not exists idx_compras_created   on public.compras(created_at);
create index if not exists idx_compras_proveedor on public.compras(proveedor_id);

create table if not exists public.compra_items (
  id             bigint generated by default as identity primary key,
  compra_id      bigint not null references public.compras(id) on delete cascade,
  producto_id    bigint references public.productos(id) on delete set null,
  cantidad       numeric not null,
  costo_unitario numeric not null
);
create index if not exists idx_compraitems_compra   on public.compra_items(compra_id);
create index if not exists idx_compraitems_producto on public.compra_items(producto_id);

-- ---------------------------------------------------------------------
-- Pérdidas (roturas, vencidos, dañados)
-- ---------------------------------------------------------------------
create table if not exists public.perdidas (
  id             bigint generated by default as identity primary key,
  producto_id    bigint references public.productos(id) on delete set null,
  cantidad       numeric not null,
  motivo         text,
  costo_unitario numeric,
  registrado_por text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_perdidas_producto on public.perdidas(producto_id);
create index if not exists idx_perdidas_created  on public.perdidas(created_at);

-- ---------------------------------------------------------------------
-- Rendimiento de consumibles ilimitados (baldes, coberturas, etc.)
-- ---------------------------------------------------------------------
create table if not exists public.helado_rendimientos (
  id          bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id) on delete cascade,
  bolas       numeric not null,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Historial / auditoría de acciones
-- ---------------------------------------------------------------------
create table if not exists public.historial (
  id          bigint generated by default as identity primary key,
  tabla       text,
  registro_id bigint,
  accion      text,           -- crear | editar | eliminar
  detalle     text,
  usuario     text,
  fecha       timestamptz not null default now()
);
alter table public.historial add column if not exists auth_uid uuid;   -- quién estaba logueado de verdad
create index if not exists idx_historial_fecha on public.historial(fecha desc);
create index if not exists idx_historial_tabla on public.historial(tabla, registro_id);

-- =====================================================================
-- TABLAS NUEVAS
-- =====================================================================

-- ---------------------------------------------------------------------
-- Pedidos / encargos (ej: una bandeja para el viernes)
-- ---------------------------------------------------------------------
create table if not exists public.pedidos (
  id              bigint generated by default as identity primary key,
  cliente_id      bigint references public.clientes(id) on delete set null,
  cliente_nombre  text,                       -- por si el cliente no está cargado
  telefono        text,
  fecha_entrega   date not null,
  estado          text not null default 'pendiente',   -- pendiente | listo | entregado | cancelado
  sena            numeric not null default 0,
  total_estimado  numeric not null default 0,
  notas           text,
  registrado_por  text,
  venta_id        bigint references public.ventas(id) on delete set null,  -- cuando se concreta
  created_at      timestamptz not null default now()
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'pedidos_estado_chk') then
    alter table public.pedidos add constraint pedidos_estado_chk
      check (estado in ('pendiente','listo','entregado','cancelado')) not valid;
  end if;
end $$;
create index if not exists idx_pedidos_estado  on public.pedidos(estado);
create index if not exists idx_pedidos_entrega on public.pedidos(fecha_entrega);

create table if not exists public.pedido_items (
  id              bigint generated by default as identity primary key,
  pedido_id       bigint not null references public.pedidos(id) on delete cascade,
  producto_id     bigint references public.productos(id) on delete set null,
  descripcion     text,
  cantidad        numeric not null default 1,
  precio_unitario numeric not null default 0
);
create index if not exists idx_pedidoitems_pedido on public.pedido_items(pedido_id);

-- ---------------------------------------------------------------------
-- Lotes (para control de vencimientos)
--   Se crea un lote por cada compra_item de un producto con vida_util_dias.
--   El stock "real" sigue viviendo en productos.stock; los lotes son la
--   capa de trazabilidad de vencimiento (FEFO).
-- ---------------------------------------------------------------------
create table if not exists public.lotes (
  id                bigint generated by default as identity primary key,
  producto_id       bigint not null references public.productos(id) on delete cascade,
  compra_id         bigint references public.compras(id) on delete set null,
  cantidad          numeric not null,
  cantidad_restante numeric not null,
  vencimiento       date,
  costo_unitario    numeric,
  created_at        timestamptz not null default now()
);
create index if not exists idx_lotes_producto on public.lotes(producto_id);
create index if not exists idx_lotes_venc     on public.lotes(vencimiento) where cantidad_restante > 0;

-- ---------------------------------------------------------------------
-- Historial de precios de compra (se llena por trigger, ver 04_triggers.sql)
-- ---------------------------------------------------------------------
create table if not exists public.precio_historial (
  id             bigint generated by default as identity primary key,
  producto_id    bigint not null references public.productos(id) on delete cascade,
  proveedor_id   bigint references public.proveedores(id) on delete set null,
  compra_id      bigint references public.compras(id) on delete set null,
  costo_unitario numeric not null,
  fecha          timestamptz not null default now()
);
create index if not exists idx_preciohist_producto on public.precio_historial(producto_id, fecha desc);

-- ---------------------------------------------------------------------
-- Registro de copias de seguridad automáticas (lo llena la Edge Function)
-- ---------------------------------------------------------------------
create table if not exists public.backups_log (
  id          bigint generated by default as identity primary key,
  archivo     text not null,
  bytes       bigint,
  filas_total bigint,
  ok          boolean not null default true,
  error       text,
  created_at  timestamptz not null default now()
);

commit;
