-- =====================================================================
-- CG DULCES · APLICAR TODO DE UNA VEZ  (seguridad + transacciones + analisis)
-- =====================================================================
-- Junta EN ORDEN:  01_schema -> 02_security -> 03_rpc -> 04_triggers -> 05_views
--
-- COMO USARLO (una sola vez):
--   1. supabase.com  ->  tu proyecto  ->  menu izquierdo "SQL Editor"
--   2. Boton  "+ New query"
--   3. Pega TODO este archivo
--   4. Boton  "Run"  (arriba a la derecha).  Debe decir  "Success".
--   5. Despues corre  VERIFICAR.sql  y manda el resultado a Claude.
--
-- Storage (fotos, comprobantes, backups) va aparte en 06_storage.sql.
-- Es seguro re-ejecutar este archivo: usa "if not exists" / "create or replace"
-- y chequeos antes de crear constraints. No borra ni cambia datos existentes.
-- =====================================================================


-- #####################################################################
-- ###  01_schema.sql
-- #####################################################################

-- =====================================================================
-- CG DULCES · Esquema de base de datos (Supabase / PostgreSQL)
-- =====================================================================
-- Este archivo reconstruye el esquema tal como lo usa index.html HOY,
-- y agrega columnas/tablas nuevas para las funciones pedidas.
--
-- ⚠ IMPORTANTE: tu base YA existe. NO ejecutes esto entero a ciegas.
--   1. Todo lo que crea tablas/columnas usa "IF NOT EXISTS" o
--      "ADD COLUMN IF NOT EXISTS": es seguro correrlo sobre la base actual.
--   2. Antes de aplicar, sacá una copia (Dashboard → Database → Backups,
--      o el botón "Descargar copia de seguridad" de la app).
--   3. Aplicá en este orden: 01_schema → 02_security → 03_rpc →
--      04_triggers → 05_views. Ver docs/MIGRATION.md.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Configuración (clave/valor)
-- ---------------------------------------------------------------------
create table if not exists public.configuracion (
  clave text primary key,
  valor text
);

-- ---------------------------------------------------------------------
-- Usuarios de la app (vendedores que aparecen al confirmar una venta)
-- ---------------------------------------------------------------------
create table if not exists public.usuarios_app (
  id          bigint generated by default as identity primary key,
  nombre      text not null unique,
  created_at  timestamptz not null default now()
);
-- NUEVO: identidad real por vendedor (Fase 2 de seguridad)
alter table public.usuarios_app add column if not exists rol        text not null default 'vendedor';   -- 'duena' | 'vendedor'
alter table public.usuarios_app add column if not exists pin_hash   text;                                -- PIN 4-6 dígitos, hasheado (nunca en texto plano)
alter table public.usuarios_app add column if not exists activo     boolean not null default true;
alter table public.usuarios_app add column if not exists auth_uid   uuid;                                -- se enlaza con auth.users cuando cada vendedor tenga su login
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'usuarios_app_rol_chk') then
    alter table public.usuarios_app add constraint usuarios_app_rol_chk
      check (rol in ('duena','vendedor')) not valid;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Categorías
-- ---------------------------------------------------------------------
create table if not exists public.categorias (
  id      bigint generated by default as identity primary key,
  nombre  text not null unique
);
alter table public.categorias add column if not exists orden  int;
alter table public.categorias add column if not exists color  text;

-- ---------------------------------------------------------------------
-- Proveedores
-- ---------------------------------------------------------------------
create table if not exists public.proveedores (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  telefono    text,
  created_at  timestamptz not null default now()
);
alter table public.proveedores add column if not exists telefono text;   -- por si acaso: refuerzo defensivo

-- ---------------------------------------------------------------------
-- Clientes
-- ---------------------------------------------------------------------
create table if not exists public.clientes (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  telefono    text,
  created_at  timestamptz not null default now()
);
alter table public.clientes add column if not exists telefono text;   -- la app original nunca lo usó: puede faltar en tablas ya existentes
alter table public.clientes add column if not exists notas text;

-- ---------------------------------------------------------------------
-- Productos e insumos
-- ---------------------------------------------------------------------
create table if not exists public.productos (
  id                    bigint generated by default as identity primary key,
  nombre                text not null,
  categoria_id          bigint references public.categorias(id) on delete set null,
  presentacion          text,
  es_insumo             boolean not null default false,
  favorito              boolean not null default false,
  usa_pajita            boolean not null default false,
  activo                boolean not null default true,
  stock                 numeric not null default 0,
  stock_minimo          numeric not null default 0,
  precio_venta          numeric not null default 0,
  costo_ultimo          numeric not null default 0,
  producto_base         text,          -- 'Balde Helado' | 'Cobertura' | null
  bolas_vendidas_actual numeric not null default 0,
  equivalencia_bolas    numeric,       -- factor de conversión al comprar (ej: 1 balde => N bolas)
  created_at            timestamptz not null default now()
);
-- NUEVO
alter table public.productos add column if not exists foto_url            text;
alter table public.productos add column if not exists precio_mayorista    numeric;      -- null = no tiene precio mayorista
alter table public.productos add column if not exists mayorista_min_cant  numeric;      -- desde cuántas unidades aplica
alter table public.productos add column if not exists vida_util_dias      int;          -- para control de vencimientos por lote
alter table public.productos add column if not exists proveedor_habitual_id bigint references public.proveedores(id) on delete set null;

create index if not exists idx_productos_activo    on public.productos(activo);
create index if not exists idx_productos_categoria on public.productos(categoria_id);
create index if not exists idx_productos_insumo    on public.productos(es_insumo);

-- ---------------------------------------------------------------------
-- Promociones
-- ---------------------------------------------------------------------
create table if not exists public.promociones (
  id                   bigint generated by default as identity primary key,
  nombre               text not null,
  categoria_id         bigint references public.categorias(id) on delete cascade,
  producto_id          bigint references public.productos(id)  on delete cascade,
  cantidad_requerida   int not null default 2,
  precio_promocional   numeric not null default 0,
  activo               boolean not null default true,
  created_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Recetas (insumos que lleva 1 unidad de un producto terminado)
-- ---------------------------------------------------------------------
create table if not exists public.recetas (
  id                    bigint generated by default as identity primary key,
  producto_terminado_id bigint not null references public.productos(id) on delete cascade,
  insumo_id             bigint not null references public.productos(id) on delete cascade,
  cantidad              numeric not null,
  created_at            timestamptz not null default now()
);
create index if not exists idx_recetas_terminado on public.recetas(producto_terminado_id);

-- ---------------------------------------------------------------------
-- Caja
-- ---------------------------------------------------------------------
create table if not exists public.caja (
  id                bigint generated by default as identity primary key,
  estado            text not null default 'abierta',   -- 'abierta' | 'cerrada'
  apertura_efectivo numeric not null default 0,
  apertura_banco    numeric not null default 0,
  cierre_efectivo   numeric,
  cierre_banco      numeric,
  fecha_apertura    timestamptz not null default now(),
  fecha_cierre      timestamptz,
  registrado_por    text
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'caja_estado_chk') then
    alter table public.caja add constraint caja_estado_chk check (estado in ('abierta','cerrada')) not valid;
  end if;
end $$;
create unique index if not exists uq_caja_una_abierta on public.caja(estado) where estado = 'abierta';

create table if not exists public.caja_movimientos (
  id           bigint generated by default as identity primary key,
  caja_id      bigint not null references public.caja(id) on delete cascade,
  tipo         text not null,                 -- venta | cobro | ingreso_extra | retiro | compra
  monto        numeric not null,
  medio_pago   text,                          -- efectivo | transferencia | qr
  venta_id     bigint,
  compra_id    bigint,
  descripcion  text,
  fecha        timestamptz not null default now()
);
alter table public.caja_movimientos add column if not exists compra_id bigint;
alter table public.caja_movimientos add column if not exists cobro_id  bigint;   -- la app original lo usaba en algunos cobros
create index if not exists idx_cajamov_caja on public.caja_movimientos(caja_id);
create index if not exists idx_cajamov_venta on public.caja_movimientos(venta_id);
create index if not exists idx_cajamov_compra on public.caja_movimientos(compra_id);

-- ---------------------------------------------------------------------
-- Ventas
-- ---------------------------------------------------------------------
create table if not exists public.ventas (
  id                  bigint generated by default as identity primary key,
  subtotal            numeric,
  descuento_total     numeric not null default 0,
  total               numeric not null,
  medio_pago          text,                    -- efectivo | transferencia | qr | mixto | fiado
  es_fiado            boolean not null default false,
  registrado_por      text,
  cliente_id          bigint references public.clientes(id) on delete set null,
  monto_efectivo      numeric not null default 0,
  monto_transferencia numeric not null default 0,
  created_at          timestamptz not null default now()
);
alter table public.ventas add column if not exists usuario_app_id bigint references public.usuarios_app(id) on delete set null;
alter table public.ventas add column if not exists es_mayorista   boolean not null default false;
alter table public.ventas add column if not exists pedido_id      bigint;   -- si nació de un encargo
create index if not exists idx_ventas_created on public.ventas(created_at);
create index if not exists idx_ventas_cliente on public.ventas(cliente_id);
create index if not exists idx_ventas_fiado   on public.ventas(es_fiado) where es_fiado;

create table if not exists public.venta_items (
  id              bigint generated by default as identity primary key,
  venta_id        bigint not null references public.ventas(id) on delete cascade,
  producto_id     bigint references public.productos(id) on delete set null,
  cantidad        numeric not null,
  precio_unitario numeric,
  costo_unitario  numeric,
  descuento       numeric not null default 0,
  subtotal        numeric
);
create index if not exists idx_ventaitems_venta    on public.venta_items(venta_id);
create index if not exists idx_ventaitems_producto on public.venta_items(producto_id);

-- Cuentas compartidas (dividir una venta entre varios clientes)
create table if not exists public.venta_repartos (
  id          bigint generated by default as identity primary key,
  venta_id    bigint not null references public.ventas(id) on delete cascade,
  cliente_id  bigint not null references public.clientes(id) on delete cascade,
  monto       numeric not null,
  created_at  timestamptz not null default now()
);
create index if not exists idx_repartos_venta   on public.venta_repartos(venta_id);
create index if not exists idx_repartos_cliente on public.venta_repartos(cliente_id);

-- ---------------------------------------------------------------------
-- Cobros de fiado
-- ---------------------------------------------------------------------
create table if not exists public.cobros (
  id             bigint generated by default as identity primary key,
  venta_id       bigint references public.ventas(id) on delete set null,
  cliente_id     bigint references public.clientes(id) on delete set null,
  monto          numeric not null,
  medio_pago     text,
  registrado_por text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_cobros_venta   on public.cobros(venta_id);
create index if not exists idx_cobros_cliente on public.cobros(cliente_id);
create index if not exists idx_cobros_created on public.cobros(created_at);

-- ---------------------------------------------------------------------
-- Compras a proveedores
-- ---------------------------------------------------------------------
create table if not exists public.compras (
  id                  bigint generated by default as identity primary key,
  proveedor_id        bigint references public.proveedores(id) on delete set null,
  tipo                text,
  total               numeric not null,
  descuento           numeric not null default 0,
  medio_pago          text,
  monto_efectivo      numeric not null default 0,
  monto_transferencia numeric not null default 0,
  comprobante_url     text,
  registrado_por      text,
  created_at          timestamptz not null default now()
);
create index if not exists idx_compras_created   on public.compras(created_at);
create index if not exists idx_compras_proveedor on public.compras(proveedor_id);

create table if not exists public.compra_items (
  id             bigint generated by default as identity primary key,
  compra_id      bigint not null references public.compras(id) on delete cascade,
  producto_id    bigint references public.productos(id) on delete set null,
  cantidad       numeric not null,
  costo_unitario numeric not null
);
create index if not exists idx_compraitems_compra   on public.compra_items(compra_id);
create index if not exists idx_compraitems_producto on public.compra_items(producto_id);

-- ---------------------------------------------------------------------
-- Pérdidas (roturas, vencidos, dañados)
-- ---------------------------------------------------------------------
create table if not exists public.perdidas (
  id             bigint generated by default as identity primary key,
  producto_id    bigint references public.productos(id) on delete set null,
  cantidad       numeric not null,
  motivo         text,
  costo_unitario numeric,
  registrado_por text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_perdidas_producto on public.perdidas(producto_id);
create index if not exists idx_perdidas_created  on public.perdidas(created_at);

-- ---------------------------------------------------------------------
-- Rendimiento de consumibles ilimitados (baldes, coberturas, etc.)
-- ---------------------------------------------------------------------
create table if not exists public.helado_rendimientos (
  id          bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id) on delete cascade,
  bolas       numeric not null,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Historial / auditoría de acciones
-- ---------------------------------------------------------------------
create table if not exists public.historial (
  id          bigint generated by default as identity primary key,
  tabla       text,
  registro_id bigint,
  accion      text,           -- crear | editar | eliminar
  detalle     text,
  usuario     text,
  fecha       timestamptz not null default now()
);
alter table public.historial add column if not exists auth_uid uuid;   -- quién estaba logueado de verdad
create index if not exists idx_historial_fecha on public.historial(fecha desc);
create index if not exists idx_historial_tabla on public.historial(tabla, registro_id);

-- =====================================================================
-- TABLAS NUEVAS
-- =====================================================================

-- ---------------------------------------------------------------------
-- Pedidos / encargos (ej: una bandeja para el viernes)
-- ---------------------------------------------------------------------
create table if not exists public.pedidos (
  id              bigint generated by default as identity primary key,
  cliente_id      bigint references public.clientes(id) on delete set null,
  cliente_nombre  text,                       -- por si el cliente no está cargado
  telefono        text,
  fecha_entrega   date not null,
  estado          text not null default 'pendiente',   -- pendiente | listo | entregado | cancelado
  sena            numeric not null default 0,
  total_estimado  numeric not null default 0,
  notas           text,
  registrado_por  text,
  venta_id        bigint references public.ventas(id) on delete set null,  -- cuando se concreta
  created_at      timestamptz not null default now()
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'pedidos_estado_chk') then
    alter table public.pedidos add constraint pedidos_estado_chk
      check (estado in ('pendiente','listo','entregado','cancelado')) not valid;
  end if;
end $$;
create index if not exists idx_pedidos_estado  on public.pedidos(estado);
create index if not exists idx_pedidos_entrega on public.pedidos(fecha_entrega);

create table if not exists public.pedido_items (
  id              bigint generated by default as identity primary key,
  pedido_id       bigint not null references public.pedidos(id) on delete cascade,
  producto_id     bigint references public.productos(id) on delete set null,
  descripcion     text,
  cantidad        numeric not null default 1,
  precio_unitario numeric not null default 0
);
create index if not exists idx_pedidoitems_pedido on public.pedido_items(pedido_id);

-- ---------------------------------------------------------------------
-- Lotes (para control de vencimientos)
--   Se crea un lote por cada compra_item de un producto con vida_util_dias.
--   El stock "real" sigue viviendo en productos.stock; los lotes son la
--   capa de trazabilidad de vencimiento (FEFO).
-- ---------------------------------------------------------------------
create table if not exists public.lotes (
  id                bigint generated by default as identity primary key,
  producto_id       bigint not null references public.productos(id) on delete cascade,
  compra_id         bigint references public.compras(id) on delete set null,
  cantidad          numeric not null,
  cantidad_restante numeric not null,
  vencimiento       date,
  costo_unitario    numeric,
  created_at        timestamptz not null default now()
);
create index if not exists idx_lotes_producto on public.lotes(producto_id);
create index if not exists idx_lotes_venc     on public.lotes(vencimiento) where cantidad_restante > 0;

-- ---------------------------------------------------------------------
-- Historial de precios de compra (se llena por trigger, ver 04_triggers.sql)
-- ---------------------------------------------------------------------
create table if not exists public.precio_historial (
  id             bigint generated by default as identity primary key,
  producto_id    bigint not null references public.productos(id) on delete cascade,
  proveedor_id   bigint references public.proveedores(id) on delete set null,
  compra_id      bigint references public.compras(id) on delete set null,
  costo_unitario numeric not null,
  fecha          timestamptz not null default now()
);
create index if not exists idx_preciohist_producto on public.precio_historial(producto_id, fecha desc);

-- ---------------------------------------------------------------------
-- Registro de copias de seguridad automáticas (lo llena la Edge Function)
-- ---------------------------------------------------------------------
create table if not exists public.backups_log (
  id          bigint generated by default as identity primary key,
  archivo     text not null,
  bytes       bigint,
  filas_total bigint,
  ok          boolean not null default true,
  error       text,
  created_at  timestamptz not null default now()
);

commit;


-- #####################################################################
-- ###  02_security.sql
-- #####################################################################

-- =====================================================================
-- CG DULCES · Seguridad (Row Level Security + permisos)
-- =====================================================================
-- QUÉ ARREGLA ESTO:
--   Hoy la "publishable key" está en el HTML público. Sin RLS, cualquiera
--   con esa clave puede LEER y BORRAR toda la base (ventas, deudas de
--   clientes, etc.). Este archivo:
--     1. Activa RLS en TODAS las tablas.
--     2. Quita todo permiso al rol "anon" (visitante sin login).
--     3. Deja acceso completo SOLO a usuarios autenticados (los que
--        entraron con usuario/contraseña).
--
-- Modelo actual: un único login compartido para el negocio.
--   -> "authenticated = todo, anon = nada" es suficiente y CIERRA el agujero.
--
-- Modelo futuro (Fase 2, un login por vendedor): al final de este archivo
--   quedan, comentadas, las políticas por rol (solo la dueña borra ventas,
--   cambia precios, gestiona usuarios). Se activan cuando cada vendedor
--   tenga su propio usuario en Supabase Auth.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Activar RLS en todas las tablas del esquema public
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'configuracion','usuarios_app','categorias','proveedores','clientes',
    'productos','promociones','recetas','caja','caja_movimientos','ventas',
    'venta_items','venta_repartos','cobros','compras','compra_items',
    'perdidas','helado_rendimientos','historial','pedidos','pedido_items',
    'lotes','precio_historial','backups_log'
  ]
  loop
    -- ENABLE: aplica RLS a los roles de la API (anon / authenticated).
    -- NO usamos FORCE a propósito: así el dueño de la tabla (rol postgres del
    -- editor SQL y la service_role) sigue viendo todo para inspeccionar y hacer
    -- backups. La app entra como "authenticated", que SÍ pasa por las políticas.
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------
-- 2. Quitar acceso directo a los roles de API salvo por políticas
--    (RLS ya lo hace, pero revocamos GRANTs por las dudas)
-- ---------------------------------------------------------------------
revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

grant usage on schema public to authenticated;
grant all on all tables    in schema public to authenticated;
grant all on all sequences in schema public to authenticated;

-- Para tablas/funciones futuras
alter default privileges in schema public grant all on tables    to authenticated;
alter default privileges in schema public grant all on sequences to authenticated;
alter default privileges in schema public revoke all on tables    from anon;

-- ---------------------------------------------------------------------
-- 3. Políticas: acceso total para usuarios autenticados
--    (se recrean de forma idempotente)
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'configuracion','usuarios_app','categorias','proveedores','clientes',
    'productos','promociones','recetas','caja','caja_movimientos','ventas',
    'venta_items','venta_repartos','cobros','compras','compra_items',
    'perdidas','helado_rendimientos','historial','pedidos','pedido_items',
    'lotes','precio_historial'
  ]
  loop
    execute format('drop policy if exists "app_read"  on public.%I;', t);
    execute format('drop policy if exists "app_write" on public.%I;', t);
    execute format($f$
      create policy "app_read" on public.%I
        for select to authenticated using (true);
    $f$, t);
    execute format($f$
      create policy "app_write" on public.%I
        for all to authenticated using (true) with check (true);
    $f$, t);
  end loop;
end $$;

-- backups_log: la app solo lo lee; lo escribe la Edge Function con service_role
drop policy if exists "backups_read" on public.backups_log;
create policy "backups_read" on public.backups_log
  for select to authenticated using (true);

commit;

-- =====================================================================
-- 4. STORAGE  ->  se configura aparte, en  supabase/06_storage.sql
--    (buckets de comprobantes, fotos de producto y backups).
--    Se dejó fuera de este archivo para que, si algo de Storage falla,
--    NO frene la parte importante (RLS). Correlo después, cuando llegue
--    la Fase 2, o junto con la Edge Function de backup.
--
-- 5. Endurecer Auth  ->  esto NO es SQL, se hace en el panel web:
--    Authentication → Sign In / Providers → Email:
--       • "Allow new users to sign up" (o "Enable Signups")  ->  APAGADO
--       • "Confirm email"                                    ->  ENCENDIDO
--    Project Settings → API:
--       • Rotá la clave "anon / publishable" DESPUÉS de aplicar RLS
--         y pegá la nueva en  js/config.js.
--       • La clave "service_role" NUNCA va en el frontend.
-- =====================================================================

-- =====================================================================
-- 6. (FUTURO · Fase 2) Políticas por rol — dejar COMENTADO por ahora
-- =====================================================================
-- Requisitos previos:
--   • Un usuario de Supabase Auth por vendedor.
--   • usuarios_app.auth_uid enlazado con auth.users.id.
--   • Helper para saber el rol del que está logueado:
--
-- create or replace function public.rol_actual() returns text
-- language sql stable security definer set search_path = public as $$
--   select coalesce(
--     (select rol from public.usuarios_app where auth_uid = auth.uid() and activo limit 1),
--     'vendedor')
-- $$;
--
-- Ejemplo: solo la dueña puede BORRAR ventas y cambiar precios de productos
--
-- drop policy if exists "app_write" on public.ventas;
-- create policy "ventas_insert" on public.ventas
--   for insert to authenticated with check (true);
-- create policy "ventas_update" on public.ventas
--   for update to authenticated using (true) with check (true);
-- create policy "ventas_delete_solo_duena" on public.ventas
--   for delete to authenticated using (public.rol_actual() = 'duena');
-- create policy "ventas_select" on public.ventas
--   for select to authenticated using (true);
--
-- (Repetir el patrón para compras, productos.precio_*, usuarios_app, etc.)
-- =====================================================================


-- #####################################################################
-- ###  03_rpc.sql
-- #####################################################################

-- =====================================================================
-- CG DULCES · Funciones transaccionales (RPC)
-- =====================================================================
-- QUÉ ARREGLA ESTO:
--   • Condición de carrera en el stock: hoy la app hace
--     "leo stock en memoria → resto → escribo". Dos ventas a la vez
--     (o desde dos celulares) se pisan y el stock queda mal.
--   • Venta a medias: si falla un paso intermedio, quedaban ventas sin
--     items, o stock descontado sin venta, o caja sin movimiento.
--
--   Ahora cada operación es UNA transacción en la base, con bloqueo de
--   fila (SELECT ... FOR UPDATE). O se hace todo, o no se hace nada.
--
-- CÓMO LO USA EL FRONTEND:
--   const { data, error } = await sb.rpc('registrar_venta', { p: {...} });
--   (los contratos JSON están documentados arriba de cada función)
--
-- Todas son SECURITY DEFINER y solo las puede ejecutar un usuario logueado.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Helpers internos
-- ---------------------------------------------------------------------

create or replace function public._hist(
  p_tabla text, p_registro_id bigint, p_accion text, p_detalle text, p_usuario text
) returns void
language sql security definer set search_path = public as $$
  insert into public.historial (tabla, registro_id, accion, detalle, usuario, auth_uid)
  values (p_tabla, p_registro_id, p_accion, p_detalle, coalesce(p_usuario,''), auth.uid());
$$;

-- Saldos de una caja (misma regla que la app: apertura +/- movimientos)
create or replace function public.saldos_caja(p_caja_id bigint)
returns table (efectivo numeric, banco numeric)
language sql stable security definer set search_path = public as $$
  select
    coalesce(c.apertura_efectivo,0) + coalesce(sum(
      case when m.medio_pago in ('transferencia','qr') then 0
           when m.tipo in ('venta','cobro','ingreso_extra') then m.monto
           else -m.monto end), 0),
    coalesce(c.apertura_banco,0) + coalesce(sum(
      case when m.medio_pago in ('transferencia','qr')
           then (case when m.tipo in ('venta','cobro','ingreso_extra') then m.monto else -m.monto end)
           else 0 end), 0)
  from public.caja c
  left join public.caja_movimientos m on m.caja_id = c.id
  where c.id = p_caja_id
  group by c.id;
$$;

create or replace function public.caja_abierta_id()
returns bigint
language sql stable security definer set search_path = public as $$
  select id from public.caja where estado = 'abierta' order by fecha_apertura desc limit 1;
$$;

-- Consumo "ilimitado mientras el paquete esté abierto" (baldes, coberturas,
-- servilletas, cucharitas, pajitas, bolsitas de hielo). Con bloqueo de fila.
create or replace function public._consumir_ilimitado(p_producto_id bigint, p_cantidad numeric)
returns void
language plpgsql security definer set search_path = public as $$
declare v_stock numeric; v_abiertas numeric; v_nombre text; v_pres text;
begin
  if p_producto_id is null or coalesce(p_cantidad,0) = 0 then return; end if;
  select stock, bolas_vendidas_actual, nombre, presentacion
    into v_stock, v_abiertas, v_nombre, v_pres
  from public.productos where id = p_producto_id for update;

  if v_abiertas is null then v_abiertas := 0; end if;

  if v_abiertas = 0 then
    if coalesce(v_stock,0) <= 0 then
      raise exception 'SIN_INSUMO: No hay más "%" disponible. Comprá o reponé el insumo.',
        coalesce(v_pres, v_nombre) using errcode = 'P0001';
    end if;
    update public.productos
      set stock = v_stock - 1, bolas_vendidas_actual = p_cantidad
      where id = p_producto_id;
  else
    update public.productos
      set bolas_vendidas_actual = v_abiertas + p_cantidad
      where id = p_producto_id;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- CAJA
-- ---------------------------------------------------------------------

-- Abrir caja. Repone lo que quedó al cerrar la última (igual que la app).
create or replace function public.abrir_caja(
  p_apertura_efectivo numeric default null,
  p_apertura_banco     numeric default null,
  p_registrado_por     text    default ''
) returns bigint
language plpgsql security definer set search_path = public as $$
declare v_id bigint; v_prev record; v_ef numeric; v_ba numeric;
begin
  if public.caja_abierta_id() is not null then
    raise exception 'CAJA_YA_ABIERTA' using errcode = 'P0001';
  end if;
  if p_apertura_efectivo is null then
    select cierre_efectivo, cierre_banco into v_prev
    from public.caja where estado = 'cerrada' order by fecha_cierre desc limit 1;
    v_ef := coalesce(v_prev.cierre_efectivo, 0);
    v_ba := coalesce(v_prev.cierre_banco, 0);
  else
    v_ef := p_apertura_efectivo; v_ba := coalesce(p_apertura_banco, 0);
  end if;

  insert into public.caja (estado, apertura_efectivo, apertura_banco, registrado_por)
  values ('abierta', v_ef, v_ba, p_registrado_por)
  returning id into v_id;

  perform public._hist('caja', v_id, 'crear',
    'Caja abierta — efectivo '||v_ef||', banco '||v_ba, p_registrado_por);
  return v_id;
end $$;

create or replace function public.cerrar_caja(
  p_caja_id bigint, p_cierre_efectivo numeric default null, p_cierre_banco numeric default null,
  p_usuario text default ''
) returns void
language plpgsql security definer set search_path = public as $$
declare v_calc record;
begin
  select * into v_calc from public.saldos_caja(p_caja_id);
  update public.caja set
    estado = 'cerrada',
    fecha_cierre = now(),
    cierre_efectivo = coalesce(p_cierre_efectivo, v_calc.efectivo),
    cierre_banco    = coalesce(p_cierre_banco,    v_calc.banco)
  where id = p_caja_id and estado = 'abierta';
  if not found then raise exception 'CAJA_NO_ABIERTA' using errcode = 'P0001'; end if;
  perform public._hist('caja', p_caja_id, 'editar', 'Caja cerrada', p_usuario);
end $$;

create or replace function public.registrar_movimiento_caja(p jsonb)
returns bigint
language plpgsql security definer set search_path = public as $$
declare v_caja bigint; v_id bigint; v_tipo text; v_monto numeric; v_medio text; v_saldos record;
begin
  v_caja := public.caja_abierta_id();
  if v_caja is null then raise exception 'CAJA_CERRADA' using errcode = 'P0001'; end if;
  v_tipo  := p->>'tipo';                    -- 'retiro' | 'ingreso_extra'
  v_monto := (p->>'monto')::numeric;
  v_medio := coalesce(p->>'medio_pago','efectivo');
  if coalesce(v_monto,0) <= 0 then raise exception 'MONTO_INVALIDO' using errcode='P0001'; end if;

  if v_tipo = 'retiro' then
    select * into v_saldos from public.saldos_caja(v_caja);
    if v_medio in ('transferencia','qr') and v_monto > v_saldos.banco then
      raise exception 'SIN_BANCO: disponible %', v_saldos.banco using errcode='P0001';
    elsif v_medio not in ('transferencia','qr') and v_monto > v_saldos.efectivo then
      raise exception 'SIN_EFECTIVO: disponible %', v_saldos.efectivo using errcode='P0001';
    end if;
  end if;

  insert into public.caja_movimientos (caja_id, tipo, monto, medio_pago, descripcion, fecha)
  values (v_caja, v_tipo, v_monto, v_medio, p->>'descripcion', now())
  returning id into v_id;

  perform public._hist('caja_movimientos', v_caja, 'crear',
    v_tipo||' de '||v_monto||coalesce(' — '||(p->>'descripcion'), ''), p->>'registrado_por');
  return v_id;
end $$;

-- ---------------------------------------------------------------------
-- VENTA  (la función central)
-- ---------------------------------------------------------------------
-- Contrato JSON:
-- {
--   "cliente_id": 12,                 -- puede ser null
--   "usuario_app_id": 3,              -- opcional (vendedor real)
--   "registrado_por": "Caro",
--   "es_fiado": false,
--   "es_mayorista": false,
--   "pedido_id": null,
--   "medio_pago": "efectivo",        -- efectivo|transferencia|qr|mixto|fiado
--   "monto_efectivo": 50000,
--   "monto_transferencia": 0,
--   "subtotal": 50000,
--   "descuento_total": 0,
--   "total": 50000,
--   "created_at": "2026-09-03T14:00:00-03:00",   -- opcional
--   "items": [
--     { "producto_id": 5, "cantidad": 2, "precio_unitario": 15000,
--       "costo_unitario": 9000, "descuento": 0, "subtotal": 30000,
--       "descontar_stock": true }
--   ],
--   "stock_extra": [ { "producto_id": 30, "cantidad": 1 } ],        -- envases helado, stock normal
--   "consumibles_ilimitados": [ { "producto_id": 21, "cantidad": 3 } ]
-- }
create or replace function public.registrar_venta(p jsonb)
returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_caja bigint;
  v_venta_id bigint;
  v_created timestamptz := coalesce((p->>'created_at')::timestamptz, now());
  v_es_fiado boolean := coalesce((p->>'es_fiado')::boolean, false);
  v_medio text := coalesce(p->>'medio_pago', 'efectivo');
  v_ef numeric := coalesce((p->>'monto_efectivo')::numeric, 0);
  v_tr numeric := coalesce((p->>'monto_transferencia')::numeric, 0);
  v_total numeric := coalesce((p->>'total')::numeric, 0);
  r record;
  v_stock numeric;
  v_nombre text;
begin
  v_caja := public.caja_abierta_id();
  if v_caja is null then raise exception 'CAJA_CERRADA' using errcode='P0001'; end if;

  -- 1) Bloquear y validar stock de todos los productos "normales" y "extra",
  --    en orden de id para evitar deadlocks.
  for r in
    select (x->>'producto_id')::bigint as pid, sum((x->>'cantidad')::numeric) as cant
    from jsonb_array_elements(coalesce(nullif(p->'items','null'::jsonb),'[]'::jsonb)) x
    where coalesce((x->>'descontar_stock')::boolean, true)
    group by 1
    union all
    select (x->>'producto_id')::bigint, sum((x->>'cantidad')::numeric)
    from jsonb_array_elements(coalesce(nullif(p->'stock_extra','null'::jsonb),'[]'::jsonb)) x
    group by 1
    order by 1
  loop
    select stock, nombre into v_stock, v_nombre
      from public.productos where id = r.pid for update;
    if v_stock is null then raise exception 'PRODUCTO_INEXISTENTE: %', r.pid using errcode='P0001'; end if;
    if r.cant > v_stock then
      raise exception 'SIN_STOCK: % (hay %, se piden %)', v_nombre, v_stock, r.cant using errcode='P0001';
    end if;
    update public.productos set stock = stock - r.cant where id = r.pid;
  end loop;

  -- 2) Insertar la venta
  insert into public.ventas (
    subtotal, descuento_total, total, medio_pago, es_fiado, registrado_por,
    cliente_id, usuario_app_id, es_mayorista, pedido_id,
    monto_efectivo, monto_transferencia, created_at
  ) values (
    coalesce((p->>'subtotal')::numeric,0), coalesce((p->>'descuento_total')::numeric,0),
    v_total, v_medio, v_es_fiado, p->>'registrado_por',
    (p->>'cliente_id')::bigint, (p->>'usuario_app_id')::bigint,
    coalesce((p->>'es_mayorista')::boolean,false), (p->>'pedido_id')::bigint,
    case when v_es_fiado then 0 else v_ef end,
    case when v_es_fiado then 0 else v_tr end,
    v_created
  ) returning id into v_venta_id;

  -- 3) Items
  insert into public.venta_items (venta_id, producto_id, cantidad, precio_unitario, costo_unitario, descuento, subtotal)
  select v_venta_id, (x->>'producto_id')::bigint, (x->>'cantidad')::numeric,
         (x->>'precio_unitario')::numeric, (x->>'costo_unitario')::numeric,
         coalesce((x->>'descuento')::numeric,0), (x->>'subtotal')::numeric
  from jsonb_array_elements(coalesce(nullif(p->'items','null'::jsonb),'[]'::jsonb)) x;

  -- 4) Consumibles ilimitados (helado, pajitas, servilletas...)
  for r in
    select (x->>'producto_id')::bigint as pid, sum((x->>'cantidad')::numeric) as cant
    from jsonb_array_elements(coalesce(nullif(p->'consumibles_ilimitados','null'::jsonb),'[]'::jsonb)) x
    group by 1 order by 1
  loop
    perform public._consumir_ilimitado(r.pid, r.cant);
  end loop;

  -- 5) Movimientos de caja (lo fiado NO entra hasta que se cobra)
  if not v_es_fiado then
    if v_ef > 0 then
      insert into public.caja_movimientos (caja_id, tipo, monto, medio_pago, venta_id, fecha, descripcion)
      values (v_caja, 'venta', v_ef, 'efectivo', v_venta_id, v_created, 'Venta #'||v_venta_id);
    end if;
    if v_tr > 0 then
      insert into public.caja_movimientos (caja_id, tipo, monto, medio_pago, venta_id, fecha, descripcion)
      values (v_caja, 'venta', v_tr, 'transferencia', v_venta_id, v_created, 'Venta #'||v_venta_id);
    end if;
  end if;

  -- 6) Si venía de un pedido, marcarlo entregado
  if (p->>'pedido_id') is not null then
    update public.pedidos set estado = 'entregado', venta_id = v_venta_id
    where id = (p->>'pedido_id')::bigint;
  end if;

  perform public._hist('ventas', v_venta_id, 'crear',
    'Venta de '||v_total||' por '||coalesce(p->>'registrado_por','')||
    case when v_es_fiado then ' (fiado)' else '' end, p->>'registrado_por');

  return v_venta_id;
end $$;

-- Anular / eliminar una venta devolviendo el stock y limpiando caja y cobros.
create or replace function public.anular_venta(p_venta_id bigint, p_motivo text default '', p_usuario text default '')
returns void
language plpgsql security definer set search_path = public as $$
declare r record;
begin
  perform 1 from public.ventas where id = p_venta_id for update;
  if not found then raise exception 'VENTA_INEXISTENTE' using errcode='P0001'; end if;

  for r in
    select producto_id as pid, sum(cantidad) as cant
    from public.venta_items where venta_id = p_venta_id and producto_id is not null
    group by 1 order by 1
  loop
    update public.productos set stock = stock + r.cant where id = r.pid;
  end loop;

  delete from public.caja_movimientos where venta_id = p_venta_id;
  delete from public.cobros           where venta_id = p_venta_id;
  delete from public.ventas           where id = p_venta_id;  -- cascada: venta_items, venta_repartos

  perform public._hist('ventas', p_venta_id, 'eliminar',
    'Venta anulada'||coalesce(' — '||nullif(p_motivo,''), ''), p_usuario);
end $$;

-- ---------------------------------------------------------------------
-- COBRO de fiado
-- ---------------------------------------------------------------------
-- { "cliente_id": 12, "venta_id": 88, "monto": 20000,
--   "medio_pago": "efectivo", "registrado_por": "Caro", "created_at": "..." }
create or replace function public.registrar_cobro(p jsonb)
returns bigint
language plpgsql security definer set search_path = public as $$
declare v_id bigint; v_caja bigint;
  v_monto numeric := coalesce((p->>'monto')::numeric,0);
  v_medio text := coalesce(p->>'medio_pago','efectivo');
  v_created timestamptz := coalesce((p->>'created_at')::timestamptz, now());
begin
  if v_monto <= 0 then raise exception 'MONTO_INVALIDO' using errcode='P0001'; end if;

  insert into public.cobros (venta_id, cliente_id, monto, medio_pago, registrado_por, created_at)
  values ((p->>'venta_id')::bigint, (p->>'cliente_id')::bigint, v_monto, v_medio,
          p->>'registrado_por', v_created)
  returning id into v_id;

  v_caja := public.caja_abierta_id();
  if v_caja is not null then
    insert into public.caja_movimientos (caja_id, tipo, monto, medio_pago, venta_id, fecha, descripcion)
    values (v_caja, 'cobro', v_monto, v_medio, (p->>'venta_id')::bigint, v_created,
            'Cobro de fiado'||coalesce(' venta #'||(p->>'venta_id'), ''));
  end if;

  perform public._hist('cobros', v_id, 'crear',
    'Cobro de '||v_monto||coalesce(' a '||(p->>'cliente_nombre'), ''), p->>'registrado_por');
  return v_id;
end $$;

-- ---------------------------------------------------------------------
-- COMPRA a proveedor
-- ---------------------------------------------------------------------
-- { "proveedor_id": 4, "tipo": "mercaderia", "registrado_por": "Caro",
--   "descuento": 0, "total": 120000, "comprobante_url": null,
--   "medio_pago": "efectivo", "monto_efectivo": 120000, "monto_transferencia": 0,
--   "created_at": "...",
--   "items": [ { "producto_id": 5, "cantidad": 10, "costo_unitario": 6000 } ] }
create or replace function public.registrar_compra(p jsonb)
returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_caja bigint; v_compra_id bigint; v_saldos record;
  v_ef numeric := coalesce((p->>'monto_efectivo')::numeric,0);
  v_tr numeric := coalesce((p->>'monto_transferencia')::numeric,0);
  v_total numeric := coalesce((p->>'total')::numeric,0);
  v_created timestamptz := coalesce((p->>'created_at')::timestamptz, now());
  r record;
begin
  v_caja := public.caja_abierta_id();
  if v_caja is null then raise exception 'CAJA_CERRADA' using errcode='P0001'; end if;

  select * into v_saldos from public.saldos_caja(v_caja);
  if v_ef > v_saldos.efectivo then
    raise exception 'SIN_EFECTIVO: disponible %, necesitás %', v_saldos.efectivo, v_ef using errcode='P0001';
  end if;
  if v_tr > v_saldos.banco then
    raise exception 'SIN_BANCO: disponible %, necesitás %', v_saldos.banco, v_tr using errcode='P0001';
  end if;

  insert into public.compras (proveedor_id, tipo, total, descuento, medio_pago,
                              monto_efectivo, monto_transferencia, comprobante_url, registrado_por, created_at)
  values ((p->>'proveedor_id')::bigint, p->>'tipo', v_total,
          coalesce((p->>'descuento')::numeric,0), coalesce(p->>'medio_pago','efectivo'),
          v_ef, v_tr, p->>'comprobante_url', p->>'registrado_por', v_created)
  returning id into v_compra_id;

  -- items (el trigger de 04_triggers.sql llena precio_historial y lotes)
  insert into public.compra_items (compra_id, producto_id, cantidad, costo_unitario)
  select v_compra_id, (x->>'producto_id')::bigint, (x->>'cantidad')::numeric, (x->>'costo_unitario')::numeric
  from jsonb_array_elements(coalesce(nullif(p->'items','null'::jsonb),'[]'::jsonb)) x;

  -- stock + costo_ultimo, con bloqueo y conversión por equivalencia_bolas
  for r in
    select (x->>'producto_id')::bigint as pid,
           sum((x->>'cantidad')::numeric) as cant,
           max((x->>'costo_unitario')::numeric) as costo
    from jsonb_array_elements(coalesce(nullif(p->'items','null'::jsonb),'[]'::jsonb)) x
    group by 1 order by 1
  loop
    update public.productos
      set stock = stock + r.cant * coalesce(equivalencia_bolas, 1),
          costo_ultimo = r.costo
      where id = r.pid;
  end loop;

  if v_ef > 0 then
    insert into public.caja_movimientos (caja_id, tipo, monto, medio_pago, compra_id, fecha, descripcion)
    values (v_caja, 'compra', v_ef, 'efectivo', v_compra_id, v_created, 'Compra #'||v_compra_id);
  end if;
  if v_tr > 0 then
    insert into public.caja_movimientos (caja_id, tipo, monto, medio_pago, compra_id, fecha, descripcion)
    values (v_caja, 'compra', v_tr, 'transferencia', v_compra_id, v_created, 'Compra #'||v_compra_id);
  end if;

  perform public._hist('compras', v_compra_id, 'crear',
    'Compra por '||v_total, p->>'registrado_por');
  return v_compra_id;
end $$;

-- ---------------------------------------------------------------------
-- PRODUCCIÓN (descuenta insumos según receta)
-- ---------------------------------------------------------------------
create or replace function public.registrar_produccion(
  p_producto_id bigint, p_cantidad numeric, p_usuario text default ''
) returns void
language plpgsql security definer set search_path = public as $$
declare r record; v_stock numeric; v_nombre text; v_det text := '';
begin
  if coalesce(p_cantidad,0) <= 0 then raise exception 'CANTIDAD_INVALIDA' using errcode='P0001'; end if;
  perform 1 from public.productos where id = p_producto_id for update;

  for r in
    select insumo_id as pid, sum(cantidad) as por_unidad
    from public.recetas where producto_terminado_id = p_producto_id
    group by 1 order by 1
  loop
    select stock, nombre into v_stock, v_nombre from public.productos where id = r.pid for update;
    if r.por_unidad * p_cantidad > coalesce(v_stock,0) then
      raise exception 'SIN_INSUMO: % (necesitás %, hay %)',
        v_nombre, r.por_unidad * p_cantidad, coalesce(v_stock,0) using errcode='P0001';
    end if;
    update public.productos set stock = stock - r.por_unidad * p_cantidad where id = r.pid;
    v_det := v_det || v_nombre || ' -' || (r.por_unidad * p_cantidad) || '  ';
  end loop;

  update public.productos set stock = stock + p_cantidad where id = p_producto_id;
  perform public._hist('productos', p_producto_id, 'editar',
    'Producción +'||p_cantidad||coalesce(' (consumió: '||nullif(trim(v_det),'')||')',' (sin receta)'), p_usuario);
end $$;

-- ---------------------------------------------------------------------
-- PÉRDIDA (roturas, vencidos)
-- ---------------------------------------------------------------------
-- { "motivo": "vencidos", "registrado_por": "Caro",
--   "items": [ { "producto_id": 5, "cantidad": 2 } ] }
create or replace function public.registrar_perdida(p jsonb)
returns void
language plpgsql security definer set search_path = public as $$
declare r record; v_stock numeric; v_nombre text; v_costo numeric;
begin
  for r in
    select (x->>'producto_id')::bigint as pid, sum((x->>'cantidad')::numeric) as cant
    from jsonb_array_elements(coalesce(nullif(p->'items','null'::jsonb),'[]'::jsonb)) x
    group by 1 order by 1
  loop
    select stock, nombre, costo_ultimo into v_stock, v_nombre, v_costo
      from public.productos where id = r.pid for update;
    if r.cant > coalesce(v_stock,0) then
      raise exception 'SIN_STOCK: % (hay %)', v_nombre, coalesce(v_stock,0) using errcode='P0001';
    end if;
    update public.productos set stock = stock - r.cant where id = r.pid;
    insert into public.perdidas (producto_id, cantidad, motivo, costo_unitario, registrado_por)
    values (r.pid, r.cant, p->>'motivo', v_costo, p->>'registrado_por');
    perform public._hist('productos', r.pid, 'editar',
      'Pérdida -'||r.cant||' '||v_nombre||coalesce(' ('||(p->>'motivo')||')',''), p->>'registrado_por');
  end loop;
end $$;

-- ---------------------------------------------------------------------
-- DIVIDIR CUENTA entre varios clientes
-- ---------------------------------------------------------------------
-- { "producto_id": 5, "cantidad": 3, "registrado_por": "Caro",
--   "created_at": "...", "clientes": [12, 15, 19] }
create or replace function public.dividir_cuenta(p jsonb)
returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_pid bigint := (p->>'producto_id')::bigint;
  v_cant numeric := coalesce((p->>'cantidad')::numeric, 1);
  v_created timestamptz := coalesce((p->>'created_at')::timestamptz, now());
  v_precio numeric; v_costo numeric; v_stock numeric; v_nombre text;
  v_total numeric; v_venta_id bigint;
  v_ids bigint[]; v_n int; v_base numeric; v_resto numeric; i int;
begin
  select array_agg(value::text::bigint) into v_ids
  from jsonb_array_elements(coalesce(nullif(p->'clientes','null'::jsonb),'[]'::jsonb));
  v_n := coalesce(array_length(v_ids,1),0);
  if v_n < 2 then raise exception 'MIN_2_CLIENTES' using errcode='P0001'; end if;

  select precio_venta, costo_ultimo, stock, nombre
    into v_precio, v_costo, v_stock, v_nombre
  from public.productos where id = v_pid for update;
  if v_cant > coalesce(v_stock,0) then
    raise exception 'SIN_STOCK: % (hay %)', v_nombre, coalesce(v_stock,0) using errcode='P0001';
  end if;

  v_total := v_precio * v_cant;

  insert into public.ventas (subtotal, descuento_total, total, medio_pago, es_fiado,
                             registrado_por, cliente_id, created_at)
  values (v_total, 0, v_total, 'fiado', true, p->>'registrado_por', null, v_created)
  returning id into v_venta_id;

  insert into public.venta_items (venta_id, producto_id, cantidad, precio_unitario, costo_unitario, descuento, subtotal)
  values (v_venta_id, v_pid, v_cant, v_precio, v_costo, 0, v_total);

  update public.productos set stock = stock - v_cant where id = v_pid;

  v_base := floor(v_total / v_n);
  v_resto := v_total - v_base * v_n;
  for i in 1 .. v_n loop
    insert into public.venta_repartos (venta_id, cliente_id, monto)
    values (v_venta_id, v_ids[i], v_base + case when i = 1 then v_resto else 0 end);
  end loop;

  perform public._hist('ventas', v_venta_id, 'crear',
    'Cuenta dividida: '||v_nombre||' ('||v_total||') entre '||v_n||' clientes', p->>'registrado_por');
  return v_venta_id;
end $$;

-- ---------------------------------------------------------------------
-- Permisos: solo usuarios logueados; nunca el visitante anónimo
-- ---------------------------------------------------------------------
do $$
declare fn text;
begin
  foreach fn in array array[
    'saldos_caja(bigint)','caja_abierta_id()','abrir_caja(numeric,numeric,text)',
    'cerrar_caja(bigint,numeric,numeric,text)','registrar_movimiento_caja(jsonb)',
    'registrar_venta(jsonb)','anular_venta(bigint,text,text)','registrar_cobro(jsonb)',
    'registrar_compra(jsonb)','registrar_produccion(bigint,numeric,text)',
    'registrar_perdida(jsonb)','dividir_cuenta(jsonb)'
  ]
  loop
    execute format('revoke all on function public.%s from public, anon;', fn);
    execute format('grant execute on function public.%s to authenticated;', fn);
  end loop;
end $$;

-- Los helpers internos no se exponen a la API
revoke all on function public._hist(text,bigint,text,text,text) from public, anon, authenticated;
revoke all on function public._consumir_ilimitado(bigint,numeric)  from public, anon, authenticated;

commit;


-- #####################################################################
-- ###  04_triggers.sql
-- #####################################################################

-- =====================================================================
-- CG DULCES · Triggers
-- =====================================================================
-- 1. Cada línea de compra deja registro en precio_historial
--    (para ver la evolución del costo por proveedor).
-- 2. Si el producto tiene vida_util_dias, se crea un lote con su
--    fecha de vencimiento estimada (para el módulo de Vencimientos).
--
-- Funcionan tanto si la compra entra por la RPC registrar_compra()
-- como si se sigue insertando desde el frontend viejo.
-- =====================================================================

begin;

create or replace function public._compra_item_after_insert()
returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_prov_id bigint;
  v_vida int;
  v_venc date;
begin
  select c.proveedor_id into v_prov_id from public.compras c where c.id = new.compra_id;

  insert into public.precio_historial (producto_id, proveedor_id, compra_id, costo_unitario, fecha)
  values (new.producto_id, v_prov_id, new.compra_id, new.costo_unitario, now());

  select vida_util_dias into v_vida from public.productos where id = new.producto_id;
  if v_vida is not null and v_vida > 0 then
    v_venc := (now() at time zone 'America/Asuncion')::date + v_vida;
    insert into public.lotes (producto_id, compra_id, cantidad, cantidad_restante, vencimiento, costo_unitario)
    values (new.producto_id, new.compra_id, new.cantidad, new.cantidad, v_venc, new.costo_unitario);
  end if;

  return new;
end $$;

drop trigger if exists trg_compra_item_ai on public.compra_items;
create trigger trg_compra_item_ai
  after insert on public.compra_items
  for each row execute function public._compra_item_after_insert();

revoke all on function public._compra_item_after_insert() from public, anon, authenticated;

commit;


-- #####################################################################
-- ###  05_views.sql
-- #####################################################################

-- =====================================================================
-- CG DULCES · Vistas de análisis (solo lectura)
-- =====================================================================
-- Alimentan: Rentabilidad, Stock muerto, Lista de reposición,
-- Historial de precios, Analítica (hora / día), Vencimientos y
-- Cierre de caja. El frontend las consulta con sb.from('v_...').select()
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Rentabilidad por producto (histórico + últimos 30/90 días)
-- ---------------------------------------------------------------------
create or replace view public.v_producto_rentabilidad as
select
  p.id,
  p.nombre,
  p.presentacion,
  cat.nombre                                    as categoria,
  p.stock,
  p.precio_venta,
  p.costo_ultimo,
  case when p.precio_venta > 0
       then round(100.0 * (p.precio_venta - p.costo_ultimo) / p.precio_venta, 1) end as margen_actual_pct,
  coalesce(sum(vi.cantidad), 0)                                              as u_hist,
  coalesce(sum(vi.subtotal), 0)                                             as ingreso_hist,
  coalesce(sum(vi.subtotal - coalesce(vi.costo_unitario,0) * vi.cantidad), 0) as ganancia_hist,
  coalesce(sum(vi.cantidad) filter (where v.created_at >= now() - interval '30 days'), 0)  as u_30d,
  coalesce(sum(vi.subtotal) filter (where v.created_at >= now() - interval '30 days'), 0)  as ingreso_30d,
  coalesce(sum(vi.cantidad) filter (where v.created_at >= now() - interval '90 days'), 0)  as u_90d,
  coalesce(sum(vi.subtotal - coalesce(vi.costo_unitario,0)*vi.cantidad)
           filter (where v.created_at >= now() - interval '90 days'), 0)                   as ganancia_90d,
  max(v.created_at)                                                          as ultima_venta,
  (now()::date - max(v.created_at)::date)                                    as dias_sin_vender
from public.productos p
left join public.categorias  cat on cat.id = p.categoria_id
left join public.venta_items vi  on vi.producto_id = p.id
left join public.ventas      v   on v.id = vi.venta_id
where p.activo and not p.es_insumo
group by p.id, cat.nombre;

-- ---------------------------------------------------------------------
-- Stock muerto: hay stock pero no se vende hace 60+ días
-- ---------------------------------------------------------------------
create or replace view public.v_stock_muerto as
select id, nombre, presentacion, categoria, stock, costo_ultimo,
       (stock * costo_ultimo)          as plata_dormida,
       ultima_venta, dias_sin_vender
from public.v_producto_rentabilidad
where stock > 0
  and (ultima_venta is null or ultima_venta < now() - interval '60 days')
order by plata_dormida desc;

-- ---------------------------------------------------------------------
-- Lista de reposición: qué comprar y cuánto
--   venta_diaria = promedio de los últimos 30 días
--   dias_cobertura = cuánto dura el stock actual a ese ritmo
--   sugerido_comprar = volver a 2x el mínimo + 1 semana de venta
-- ---------------------------------------------------------------------
create or replace view public.v_reposicion as
with venta30 as (
  select vi.producto_id, sum(vi.cantidad) as c
  from public.venta_items vi
  join public.ventas v on v.id = vi.venta_id
  where v.created_at >= now() - interval '30 days'
  group by 1
)
select
  p.id, p.nombre, p.presentacion,
  cat.nombre                                   as categoria,
  prov.nombre                                  as proveedor,
  prov.telefono                                as proveedor_telefono,
  p.stock, p.stock_minimo,
  coalesce(v30.c, 0)                           as vendido_30d,
  round(coalesce(v30.c,0) / 30.0, 2)           as venta_diaria,
  case when coalesce(v30.c,0) > 0
       then round(p.stock / (coalesce(v30.c,0) / 30.0), 1) end as dias_cobertura,
  greatest(
    0,
    ceil( (p.stock_minimo * 2) - p.stock + (coalesce(v30.c,0) / 30.0) * 7 )
  )                                            as sugerido_comprar
from public.productos p
left join public.categorias  cat  on cat.id = p.categoria_id
left join public.proveedores prov on prov.id = p.proveedor_habitual_id
left join venta30 v30 on v30.producto_id = p.id
where p.activo and not p.es_insumo
  and ( p.stock <= p.stock_minimo
        or (coalesce(v30.c,0) > 0 and p.stock / (coalesce(v30.c,0)/30.0) < 7) )
order by dias_cobertura nulls first, p.nombre;

-- ---------------------------------------------------------------------
-- Historial de precios de compra (con variación vs. la compra anterior)
-- ---------------------------------------------------------------------
create or replace view public.v_precio_historial as
select
  ph.id,
  ph.fecha,
  p.nombre                                        as producto,
  p.presentacion,
  prov.nombre                                     as proveedor,
  ph.costo_unitario,
  lag(ph.costo_unitario) over (partition by ph.producto_id order by ph.fecha) as costo_anterior,
  ph.costo_unitario
    - lag(ph.costo_unitario) over (partition by ph.producto_id order by ph.fecha) as variacion,
  case when lag(ph.costo_unitario) over (partition by ph.producto_id order by ph.fecha) > 0
       then round(100.0 * (ph.costo_unitario
            - lag(ph.costo_unitario) over (partition by ph.producto_id order by ph.fecha))
            / lag(ph.costo_unitario) over (partition by ph.producto_id order by ph.fecha), 1)
  end                                             as variacion_pct
from public.precio_historial ph
join public.productos p       on p.id = ph.producto_id
left join public.proveedores prov on prov.id = ph.proveedor_id
order by ph.fecha desc;

-- ---------------------------------------------------------------------
-- Analítica simple: a qué hora y qué día se vende más
-- ---------------------------------------------------------------------
create or replace view public.v_ventas_por_hora as
select
  extract(hour from (v.created_at at time zone 'America/Asuncion'))::int as hora,
  count(*)        as cant_ventas,
  sum(v.total)    as total
from public.ventas v
group by 1 order by 1;

create or replace view public.v_ventas_por_dia_semana as
select
  extract(isodow from (v.created_at at time zone 'America/Asuncion'))::int as dia_num,
  to_char((v.created_at at time zone 'America/Asuncion'), 'TMDay')          as dia,
  count(*)     as cant_ventas,
  sum(v.total) as total
from public.ventas v
group by 1, 2 order by 1;

-- ---------------------------------------------------------------------
-- Vencimientos: lotes con saldo, ordenados por el que vence primero
-- ---------------------------------------------------------------------
create or replace view public.v_vencimientos as
select
  l.id,
  p.nombre                                   as producto,
  p.presentacion,
  l.cantidad_restante,
  l.vencimiento,
  (l.vencimiento - (now() at time zone 'America/Asuncion')::date) as dias_para_vencer,
  l.costo_unitario,
  (l.cantidad_restante * coalesce(l.costo_unitario,0))            as plata_en_riesgo
from public.lotes l
join public.productos p on p.id = l.producto_id
where l.cantidad_restante > 0 and l.vencimiento is not null
order by l.vencimiento;

-- ---------------------------------------------------------------------
-- Cierre de caja: resumen por caja (para el "Cierre Z" compartible)
-- ---------------------------------------------------------------------
create or replace view public.v_cierre_caja as
select
  c.id                as caja_id,
  c.estado,
  c.fecha_apertura,
  c.fecha_cierre,
  c.registrado_por,
  c.apertura_efectivo,
  c.apertura_banco,
  c.cierre_efectivo,
  c.cierre_banco,
  coalesce(sum(m.monto) filter (where m.tipo='venta' and m.medio_pago='efectivo'), 0)      as ventas_efectivo,
  coalesce(sum(m.monto) filter (where m.tipo='venta' and m.medio_pago in ('transferencia','qr')), 0) as ventas_banco,
  coalesce(sum(m.monto) filter (where m.tipo='cobro' and m.medio_pago='efectivo'), 0)      as cobros_efectivo,
  coalesce(sum(m.monto) filter (where m.tipo='cobro' and m.medio_pago in ('transferencia','qr')), 0) as cobros_banco,
  coalesce(sum(m.monto) filter (where m.tipo='ingreso_extra'), 0)                          as ingresos_extra,
  coalesce(sum(m.monto) filter (where m.tipo='retiro'), 0)                                 as retiros,
  coalesce(sum(m.monto) filter (where m.tipo='compra'), 0)                                 as compras,
  count(distinct m.venta_id) filter (where m.tipo='venta')                                 as nro_ventas,
  (select s.efectivo from public.saldos_caja(c.id) s)                                      as esperado_efectivo,
  (select s.banco    from public.saldos_caja(c.id) s)                                      as esperado_banco,
  case when c.cierre_efectivo is not null
       then c.cierre_efectivo - (select s.efectivo from public.saldos_caja(c.id) s) end    as diferencia_efectivo,
  case when c.cierre_banco is not null
       then c.cierre_banco - (select s.banco from public.saldos_caja(c.id) s) end          as diferencia_banco
from public.caja c
left join public.caja_movimientos m on m.caja_id = c.id
group by c.id;

-- Permisos de lectura
do $$
declare v text;
begin
  foreach v in array array[
    'v_producto_rentabilidad','v_stock_muerto','v_reposicion','v_precio_historial',
    'v_ventas_por_hora','v_ventas_por_dia_semana','v_vencimientos','v_cierre_caja'
  ]
  loop
    execute format('revoke all on public.%I from anon;', v);
    execute format('grant select on public.%I to authenticated;', v);
  end loop;
end $$;

commit;

